version: '3.3'

services:
  db1:
    image: mysql:5.7
    command: --innodb-log-file-size=500M --innodb_strict_mode=0
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root

  dev1:
    depends_on:
      - db1
    image: rapporteket/ablanor-dev:nightly
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
    ports:
      - "8787:8787"
      - "3838:3838"
    dns:
      - 8.8.8.8
    restart: "no"
    environment:
      PASSWORD: password
      DB_HOST: db1
      DB_USER: root
      DB_PASS: root

  adminer1:
    depends_on:
      - db1
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
